- name: Deploy Jellyfin container
  hosts: node_0
  remote_user: server-admin
  become: yes

  - name: Create container
    docker_container:
      name: jellyfin
      image: jellyfin/jellyfin
      user: root:root
      restart_policy: always
      network_mode: host
      read_only: no
      volumes:
        - "/config/jellyfin_config:/config"
        - "/mnt/hdd_0:/mnt/hdd_0"
        - "/mnt/usb_0:/mnt/usb_0"
